.dockerignore, .gitignore
This will fix docker builds failed.
=> Negating localhost* in ignores

hstream-store/admin/HStream/Store/Admin/Command.hs, hstream-store/admin/HStream/Store/Admin/Command/CheckImpact.hs, hstream-store/admin/HStream/Store/Admin/Types.hs, hstream-store/admin/app/cli.hs, hstream-store/admin/hstore-admin.cabal
=> implement basic function of check-impact command

hstream-store/HStream/Store.hs, hstream-store/HStream/Store/Exception.hs, hstream-store/HStream/Store/Internal/Foreign.hs, hstream-store/HStream/Store/Internal/LogDevice.hs, hstream-store/HStream/Store/Internal/LogDevice/LogConfigTypes.hs, hstream-store/HStream/Store/Internal/Types.hsc, hstream-store/cbits/hs_logdevice.cpp, hstream-store/hstream-store.cabal, hstream-store/include/hs_logdevice.h, hstream-store/test/HStream/StoreSpec.hs
Added another logdevice api: findTime.
Fixes #204 
I also changed `withAsyncPrimUnsafe2` slightly to check the return value from the async call in case the request failed to be submitted.
See `StoreSpec.hs`
=> logdevice api: findTime

hstream-server/src/HStream/Server/Handler.hs, hstream-server/src/HStream/Server/Utils.hs, hstream/HStream/Format.hs, hstream/client/Main.hs
- Refactor code in Server/Handler
- Fix Create Stream error message 
- I have added new tests that prove my fix is effective or that my feature works
- I have checked my code and corrected any **misspellings**
- My code follows the [**style guidelines**](https://docs.hstream.io/development/haskell-style/) of this project
- I have made corresponding changes to the documentation
- My changes generate no new warnings
- Any dependent changes have been merged and published in downstream modules
=> some code refactoring

hstream-store/HStream/Store/Internal/LogDevice.hs, hstream-store/cbits/hs_logdevice.cpp, hstream-store/include/hs_logdevice.h, hstream-store/test/HStream/StoreSpec.hs
Implemented async version of the `getTailLSN` api call.
Fixes #234 
A testcase is added to `StoreSpec.hs`
=> hstore api: async getTailLSN

hstream-store/test/HStream/StoreSpec.hs
Added tests for the logdevice api `findTime`.
Fixes #215 
=> hstore api: add tests for findTime

hstream/common/proto/HStream/Server/HStreamApi.proto, hstream/src/HStream/Server/Handler.hs
- Append
- Subscribe
- Fetch
- CommitOffset
- CreateStreams
=> add more RPC interfaces

hstream/common/proto/HStream/Server/HStreamApi.proto, hstream/src/HStream/Server/Handler.hs
Add rpc function removeStream
Manually test
=> add rpc removeStream

hstream-store/app/hstoreWriteBenchTool.hs, hstream-store/hstream-store.cabal
Implement hstore write performance bench tool.
Manually test
=> implement hstore write bench tool

hstream-store/app/writeBench.hs
fix the wrong payload generate strategy
Manually test
=> fix payload generate strategy

hstream-store/HStream/Store/Internal/LogDevice/LogConfigTypes.hs, hstream-store/admin/HStream/Store/Admin/Command/Logs.hs, hstream-store/admin/HStream/Store/Admin/Types.hs, hstream-store/cbits/logdevice/hs_logconfigtypes.cpp, hstream-store/include/hs_logdevice.h
Implemented ldshell command `logs update`
Part of #274
=> hstore admin: command logs update

hstream-store/app/writeBench.hs
support appendBatch benchmark
Manually test
=> hstream-store: support appendBatch benchmark

hstream/src/HStream/Server/Exception.hs, hstream/src/HStream/Server/Handler.hs, hstream/src/HStream/Server/Persistence.hs
=> handle exceptions together at top level of executehandler

hstream/app/server.hs, hstream/hstream.cabal
=> add logo for server

hstream-store/app/writeBench.hs, hstream-store/hstream-store.cabal
Support parallel-write benchmark.
Manually test
=> hstream-store: support parallel-write bench

script/dev-tools
Print some more info after cluster started.
=> feat: print cluster admin info after cluster launched

hstream/src/HStream/Server/Persistence.hs
=> add remove' in persistence

hstream/common/proto/HStream/Server/HStreamApi.proto, hstream/src/HStream/Server/Handler.hs
Replace `append` method to `appendBatch` in `appendHandler`
=> hstream-server:use appendbatch in applendHandler

hie.yaml, hstream-http-server/src/HStream/HTTP/Server/Query.hs, hstream-sql/etc/SQL.cf, hstream-sql/src/HStream/SQL/Codegen.hs, hstream-sql/src/HStream/SQL/Validate.hs, hstream/common/src/HStream/Utils/Format.hs, hstream/src/HStream/Server/Exception.hs, hstream/src/HStream/Server/Handler.hs, hstream/src/HStream/Server/Persistence.hs
=> add create view

hstream/common/proto/HStream/Server/HStreamApi.proto, hstream/src/HStream/Server/Handler.hs
=> hstream-server: Use new append proto

hstream/common/proto/HStream/Server/HStreamApi.proto, hstream/src/HStream/Server/Handler.hs, hstream/test/HStream/RunSQLSpec.hs
expose terminate query grpc api
=> feat: support terminate query grpc api

hstream/common/proto/HStream/Server/HStreamApi.proto, hstream/hstream.cabal, hstream/src/HStream/Server/Handler.hs
Update and implement `subscibe`, `fetch` and `commitOffset` proto
=> hstream-server: Update proto

Makefile, hstream/common/hstream-common.cabal, hstream/common/proto/HStream/Server/HStreamApi.proto, hstream/common/proto/third_party/google/protobuf/empty.proto, hstream/src/HStream/Server/Handler.hs, hstream/src/HStream/Server/Handler/Common.hs, hstream/test/HStream/Common.hs
Update proto: `deleteStreams`, `listStreams`, `createStreams`
=> hstream-server: update proto: deleteStreams, listStreams, createStreams

hstream/common/src/HStream/Utils/BuildRecord.hs
=> fix wrong use of Aeson encode

hstream/common/src/HStream/Utils/BuildRecord.hs, hstream/src/HStream/Server/Handler.hs
=> hstream-server: fill timestamp in append record

hstream/hstream.cabal, hstream/src/HStream/Server/Handler.hs, hstream/src/HStream/Server/Handler/Connector.hs, hstream/test/HStream/Common.hs, hstream/test/HStream/RunConnectorSpec.hs, hstream/test/HStream/RunQuerySpec.hs
fix hstream server and related test warnings.
=> fix: fix warnings

hstream/common/proto/HStream/Server/HStreamApi.proto, hstream/hstream.cabal, hstream/src/HStream/Server/Handler.hs, hstream/src/HStream/Server/Handler/Common.hs, hstream/src/HStream/Server/Handler/Query.hs, hstream/src/HStream/Server/Handler/View.hs, hstream/src/HStream/Server/Persistence.hs, hstream/test/HStream/RunViewSpec.hs
=> feat: support view grpc apis

hstream-store/admin/HStream/Store/Admin/Command.hs, hstream-store/admin/HStream/Store/Admin/Command/Maintenance.hs, hstream-store/admin/HStream/Store/Admin/Types.hs, hstream-store/admin/app/cli.hs, hstream-store/admin/hstore-admin.cabal
=> hadmin: maintenance list

hstream-http-server/app/Main.hs, hstream-http-server/hstream-http-server.cabal, hstream-http-server/src/HStream/HTTP/Server/API.hs, hstream-http-server/src/HStream/HTTP/Server/Connector.hs, hstream-http-server/src/HStream/HTTP/Server/Node.hs, hstream-http-server/src/HStream/HTTP/Server/Overview.hs, hstream-http-server/src/HStream/HTTP/Server/Query.hs, hstream-http-server/src/HStream/HTTP/Server/Stream.hs, hstream-http-server/src/HStream/HTTP/Server/View.hs
=> support view and query server using grpc apis

hstream-store/admin/HStream/Store/Admin/Command/Maintenance.hs, hstream-store/admin/HStream/Store/Admin/Types.hs
=> hadmin: maintenance show

hstream/hstream.cabal, hstream/src/HStream/Server/Handler.hs, hstream/test/HStream/Common.hs, hstream/test/HStream/HandlerSpec.hs, hstream/test/HStream/RegressionSpec.hs, hstream/test/HStream/RunConnectorSpec.hs, hstream/test/HStream/RunQuerySpec.hs, hstream/test/HStream/RunSQLSpec.hs, hstream/test/HStream/RunViewSpec.hs
This pr focus on two things:
1. fix some RPC handler's logic
2. add RPC handler test
Unit test
=> hstream-server: update handler and fix test

hstream-store/admin/HStream/Store/Admin/Command/Maintenance.hs, hstream-store/admin/HStream/Store/Admin/Types.hs, script/dev-tools
=> hadmin: maintenance apply

hstream-store/admin/HStream/Store/Admin/Command/Maintenance.hs, hstream-store/admin/HStream/Store/Admin/Types.hs
=> hadmin: maintenance remove

hstream-store/HStream/Store.hs, hstream-store/admin/HStream/Store/Admin/API.hs, hstream-store/admin/HStream/Store/Admin/Command.hs, hstream-store/admin/HStream/Store/Admin/Command/SQL.hs, hstream-store/admin/HStream/Store/Admin/Types.hs, hstream-store/admin/app/cli.hs, hstream-store/admin/hstore-admin.cabal
=> hadmin: interactive sql shell

hstream/src/HStream/Server/Handler.hs, hstream/src/HStream/Server/Handler/Common.hs, hstream/src/HStream/Server/Handler/Connector.hs
=> feat: support restart connector

hstream/test/HStream/HandlerSpec.hs, hstream/test/HStream/SpecUtils.hs
=> hstream-server: refactor HandlerSpec

hstream/test/HStream/HandlerSpec.hs
=> hstream-server: fix grpc response in HandlerSpec

.github/workflows/ci.yml, common/proto/HStream/Server/HStreamApi.proto, hstream-http-server/app/Main.hs, hstream-http-server/hstream-http-server.cabal, hstream-http-server/src/HStream/HTTP/Server/API.hs, hstream-http-server/src/HStream/HTTP/Server/Connector.hs, hstream-http-server/src/HStream/HTTP/Server/Node.hs, hstream-http-server/src/HStream/HTTP/Server/Overview.hs, hstream-http-server/src/HStream/HTTP/Server/Query.hs, hstream-http-server/src/HStream/HTTP/Server/Stream.hs, hstream-http-server/src/HStream/HTTP/Server/View.hs, hstream/app/server.hs, hstream/hstream.cabal, hstream/src/HStream/Server/Handler.hs, hstream/src/HStream/Server/Handler/Common.hs, hstream/src/HStream/Server/Handler/StoreAdmin.hs, hstream/test/HStream/RunStoreAdminSpec.hs
move nodes related logic to hstream-server
=> refactor http server; using gRPC server as it backend

.github/workflows/ci.yml, hstream-http-server/hstream-http-server.cabal, hstream-http-server/src/HStream/HTTP/Server/Connector.hs, hstream-http-server/src/HStream/HTTP/Server/Node.hs, hstream-http-server/src/HStream/HTTP/Server/Query.hs, hstream-http-server/src/HStream/HTTP/Server/Stream.hs, hstream-http-server/src/HStream/HTTP/Server/View.hs, hstream-http-server/test/HStream/RunConnectorSpec.hs, hstream-http-server/test/HStream/RunNodeSpec.hs, hstream-http-server/test/HStream/RunQuerySpec.hs, hstream-http-server/test/HStream/RunStreamSpec.hs, hstream-http-server/test/HStream/RunViewSpec.hs, hstream-http-server/test/HStream/SpecUtils.hs, hstream-http-server/test/Spec.hs, script/dev-tools
=> support http tests

hstream-sql/test/HStream/SQL/ParseRefineSpec.hs, hstream-sql/test/HStream/SQL/ValidateSpec.hs
=> sql: more tests

hstream/src/HStream/Server/Handler/Common.hs, hstream/src/HStream/Server/Handler/Connector.hs, hstream/src/HStream/Server/Handler/Query.hs, hstream/src/HStream/Server/Initialization.hs, hstream/src/HStream/Server/InternalHandler.hs, hstream/src/HStream/Server/Persistence/Common.hs, hstream/src/HStream/Server/Persistence/Tasks.hs, hstream/src/HStream/Server/Types.hs
=> minor fix on #618

Makefile, common/cbits/checks.h, common/cbits/query.cpp, common/cbits/query/tables/AdminCommandTable.cpp, common/clients/cpp/AdminClient.cpp, hstream/app/client.hs, hstream/hstream.cabal, hstream/src/HStream/Client/Gadget.hs
- Fixes program terminates while an error happens.
- Re-implement hstream-client admin SQL.
=> Support "normal" sql statement in hstream-client admin shell

script/dev-tools
Fix https://github.com/hstreamdb/hstream/pull/654
---
=> dev-tools: fix swagger-start

hstream-http-server/go.mod, hstream-http-server/main.go, hstream-http-server/src/append.go, hstream-http-server/src/common.go, hstream-store/app/writeBench.hs, hstream-store/hstream-store.cabal
Main changes: 
- Catch exception when decode error occurs
---
=> hstream-http-server: decode error handling

hstream-http-server/main.go, hstream-http-server/src/append.go, hstream-http-server/test/stream_test.go
=> hstream-http-server: command line flag `httpServerHost`

common/HStream/Utils/Format.hs
Main changes: 
change misleading output message from "Done. No Results." to "Done"
---
=> change cli success message to "done"

hstream/src/HStream/Server/Config.hs, script/start-server.sh
=> fix store config path option

.github/workflows/publish.yml, .github/workflows/publish_latest.yml
=> ci: trigger repository_dispatch when image pushed

common/HStream/Utils.hs, common/HStream/Utils/Format.hs, common/HStream/Utils/Table.hs, common/hstream-common.cabal, hstream-store/HStream/Store/Internal/LogDevice/Reader.hs, hstream-store/admin/HStream/Store/Admin/Command/CheckImpact.hs
=> common: support auto break for table printing

script/dev-deploy
Main changes: 
- support store command to create/update zk node
---
=> dev-deploy: add store command for zk

script/dev-deploy
Main changes: 
- update `HStoreService` to support create/destroy persistent directory 
- add `bootstrap` command to bootstrap hstore cluster
---
=> [skip ci] dev-deploy: update `HStoreService` and add bootstrap command

script/conf_example.json, script/dev-deploy
Main changes: 
- add simple service to support quick start/stop a cluster
---
=> [skip ci] dev-deploy: add simple service

hstream/src/HStream/Server/Persistence/Exception.hs, hstream/src/HStream/Server/Persistence/Tasks.hs, hstream/src/HStream/Server/Persistence/Utils.hs
Main changes: 
Reimplement some operations to be atomic
---
=> reimplement some zk operations to be atomic

common/HStream/Common/ConsistentHashing.hs, common/hstream-common.cabal, common/test/HStream/ConsistentHashingSpec.hs
> https://github.com/hstreamdb/hstream/pull/685
=> Re: consistent hashing algorithm

.hlint.yaml, hstream/src/HStream/Server/Handler/Subscription.hs, hstream/src/HStream/Server/Initialization.hs, hstream/src/HStream/Server/Persistence/Common.hs, hstream/src/HStream/Server/Persistence/Object.hs, hstream/src/HStream/Server/Persistence/Tasks.hs, hstream/src/HStream/Server/Persistence/Utils.hs, hstream/src/HStream/Server/Types.hs
Refactor
Main changes: 
- Remove unused codes and Reorganize zk paths
- Make some of the zk operations atomic
---
=> improvements on zk usage

common/HStream/Utils/Converter.hs, common/HStream/Utils/RPC.hs, hstream/src/HStream/Server/Handler/Admin.hs, hstream/src/HStream/Server/Initialization.hs, hstream/src/HStream/Server/Persistence/Nodes.hs
Add an admin command for getting the status of the cluster
---
=> add admin command status

common/HStream/Utils/RPC.hs, hstream-store/HStream/Store/Stream.hs, hstream/src/HStream/Server/Handler.hs, hstream/src/HStream/Server/Handler/Common.hs, hstream/src/HStream/Server/Handler/Query.hs, hstream/src/HStream/Server/Handler/Stream.hs, hstream/src/HStream/Server/Persistence/MemoryStore.hs
=> minor improvements

common/HStream/Utils.hs, common/hstream-common.cabal, hstream-store/admin/HStream/Store/Admin/Types.hs
=> common utils: custom aeson options

hstream/src/HStream/Server/Initialization.hs
Main changes: 
Creating the server znode and writing status were not atomic. This could cause some issues.
However, note that this pr will cause: 
- starting hservers will no longer be happening in parallel.
- the status running does not fully reflect running, however, if we want an actual running, two things are needed
+ some call back when grpc server is successfully started
+ a consistent algorithm to oversee the whole cluster
---
=> make creating server path and writing status into zk an atomic operation

script/dev-tools
=> [skip ci] dev-tools: minor fix

hstream/src/HStream/Server/Persistence/Object.hs
Main changes: 
When creating a subscription with an existing id, the behaviour should not be the old one being overridden but the new should fail
---
=> create a subcription with occupied id should not override

hstream/src/HStream/Server/Core/Stream.hs, hstream/src/HStream/Server/Handler/Stream.hs, hstream/src/HStream/Server/Handler/Subscription.hs, script/dev-tools
fix update-images script && update some log msg
=> fix update-images script && update some log msg

common/HStream/Utils/Format.hs, docker/quick-start.yaml, hstream-admin/HStream/Admin/Types.hs, hstream/hstream.cabal, hstream/src/HStream/Server/Core/View.hs, hstream/src/HStream/Server/Handler/Admin.hs, hstream/src/HStream/Server/Handler/View.hs
Main changes: hstream-admin: support view list
---
=> Hstream admin view list

conf/hstream.yaml, hstream/src/HStream/Server/Config.hs
Main changes: 
Config does not read the config file correctly
---
=> config: minor fixes

hstream-store/HStream/Store.hs, hstream-store/HStream/Store/Internal/LogDevice/Checkpoint.hs, hstream-store/HStream/Store/Stream.hs, hstream-store/cbits/logdevice/hs_checkpoint.cpp, hstream-store/hstream-store.cabal, hstream-store/test/HStream/Store/CheckpointStoreSpec.hs
=> hstore: add remove checkpoints

hstream/src/HStream/Server/Handler/Subscription.hs
Main changes: 
- fix: the consumer should re-consume from the checkpoint after server restart
---
=> hstream-server: consumer should re-consume from checkpoint after server restart

hstream-connector/HStream/Connector/HStore.hs, hstream-processing/hstream-processing.cabal, hstream-processing/src/HStream/Processing/Processor.hs, hstream-processing/src/HStream/Processing/Type.hs, hstream-store/HStream/Store/Internal/LogDevice/LogConfigTypes.hs, hstream-store/HStream/Store/Internal/Types.hsc, hstream-store/HStream/Store/Stream.hs, hstream-store/cbits/logdevice/hs_logconfigtypes.cpp, hstream-store/hstream-store.cabal, hstream-store/test/HStream/Store/CheckpointStoreSpec.hs, hstream-store/test/HStream/Store/LogDeviceSpec.hs, hstream-store/test/HStream/Store/StreamSpec.hs, hstream/src/HStream/Server/Core/Stream.hs, hstream/src/HStream/Server/Handler/Subscription.hs, hstream/test/HStream/RegressionSpec.hs
=> refactoring stream with logdir

.github/workflows/publish.yml, .github/workflows/publish_latest.yml
Main changes: include commit sha in dispatch client payload
r+ @4eUeP 
---
=> ci: include commit sha in dispatch client payload

hstream/src/HStream/Client/Execute.hs
=> fix cli error message

.github/workflows/publish.yml, .github/workflows/publish_latest.yml
Main changes: fix get commit sha on repo dispatch
sorry :(
r+ @4eUeP 
---
=> fix: get commit sha

hie.yaml, hstream-admin/HStream/Admin/Types.hs, hstream-admin/HStream/Store/Admin/Types.hs, hstream-admin/app/admin.hs, hstream-admin/app/cli.hs, hstream-admin/hstream-admin.cabal, hstream-store/HStream/Store/Internal/LogDevice/LDQuery.hs, hstream-store/cbits/logdevice/hs_ldquery.cpp, script/dev-deploy, script/dev-tools, script/wait-for-storage.sh
=> rename "hadmin" to "hadmin store" && add hadmin server

hstream/hstream.cabal, hstream/src/HStream/Server/Core/Subscription.hs, hstream/src/HStream/Server/Exception.hs, hstream/src/HStream/Server/Handler/Subscription.hs, hstream/src/HStream/Server/Persistence/Object.hs
Main changes: 
deleteSubcription
---
=> code refactoring: delete subscription

hstream/src/HStream/Server/Core/Stream.hs, hstream/src/HStream/Server/Handler/Stream.hs
Main changes: 
- fix: add partition key to verify serverID when handle append req
---
=> hstream-server: add partition key to verify serverID when handle append req

hstream/src/HStream/Client/Gadget.hs
=> fix cli insert

hstream-admin/HStream/Admin/Server/Types.hs, hstream/src/HStream/Server/Core/Subscription.hs, hstream/src/HStream/Server/Exception.hs, hstream/src/HStream/Server/Handler/Admin.hs, hstream/src/HStream/Server/Handler/Common.hs, hstream/src/HStream/Server/Handler/Stream.hs, hstream/src/HStream/Server/Handler/Subscription.hs, hstream/src/HStream/Server/Persistence/Utils.hs
Main changes: 
- create a new zk path to store relations between subscription and store
---
=> hstream-server: bind subscription to stream

hstream-admin/HStream/Admin/Server/Types.hs, hstream/src/HStream/Server/Handler/Admin.hs
=> add admin command for create subscription

common/HStream/Utils/BuildRecord.hs, hstream/src/HStream/Server/Core/Stream.hs, hstream/src/HStream/Server/Exception.hs, hstream/src/HStream/Server/Handler/Cluster.hs, hstream/src/HStream/Server/Handler/Common.hs, hstream/src/HStream/Server/Handler/Stream.hs, hstream/src/HStream/Server/Handler/Subscription.hs
- add default key
- create new partition in `lookupStream` function
=> hstream-server: minor improvement

hstream/src/HStream/Server/Handler/Subscription.hs
Main changes: fix `deleteSubscriptionHandler`
---
=> fix: `deleteSubscriptionHandler`, check exist

hstream/src/HStream/Server/Types.hs
Main changes: update server version to `0.7.0`
---
=> fix: update server version

hstream/src/HStream/Client/Execute.hs, hstream/src/HStream/Client/Gadget.hs
=> minor fix on cli

common/HStream/Common/ConsistentHashing.hs, hstream/src/HStream/Server/Handler/Common.hs, hstream/src/HStream/Server/Handler/Stream.hs, hstream/src/HStream/Server/Handler/Subscription.hs
Main changes:
some refactor
---
=> add getAllocatedNodeId

hstream/src/HStream/Server/Core/Stream.hs, hstream/src/HStream/Server/Core/Subscription.hs, hstream/src/HStream/Server/Core/View.hs, hstream/src/HStream/Server/Exception.hs
Main changes: 
refactor server core modules
---
=> Refactor core

hstream/src/HStream/Client/Execute.hs, hstream/src/HStream/Server/Handler/Cluster.hs, hstream/src/HStream/Server/Handler/Common.hs, hstream/src/HStream/Server/Handler/Stream.hs
=> fix look up stream

hstream/app/server.hs, hstream/src/HStream/Server/Config.hs
=> disable internal port

hstream/src/HStream/Server/Core/Stream.hs, hstream/src/HStream/Server/Exception.hs, hstream/src/HStream/Server/Handler/Common.hs, hstream/src/HStream/Server/Persistence/Utils.hs
=> minor fix on create stream

.github/workflows/ci.yml, script/dev-deploy, script/dev_deploy_conf_example.json
Main changes: upload store configuration to remote host
---
=> [skip ci] dev-deploy: upload store conf

hstream-store/HStream/Store/Stream.hs, hstream-store/test/HStream/Store/StreamSpec.hs
=> add findPartitions

script/dev-deploy, script/dev_deploy_conf_example.json
Main changes: config option for docker image tag
---
=> [skip ci] dev-deploy: config option for docker image tag, rm upload zk cfg

hstream-admin/HStream/Admin/Store/Command/Logs.hs, hstream-admin/HStream/Admin/Store/Types.hs, hstream-store/HStream/Store/Internal/LogDevice/LogAttributes.hs, hstream-store/HStream/Store/Internal/LogDevice/LogConfigTypes.hs, hstream-store/HStream/Store/Internal/Types.hsc, hstream-store/HStream/Store/Stream.hs, hstream-store/test/HStream/Store/ReaderSpec.hs, hstream-store/test/HStream/Store/StreamSpec.hs, hstream/src/HStream/Server/Core/Stream.hs, hstream/src/HStream/Server/Handler/Query.hs, hstream/src/HStream/Server/Handler/View.hs, hstream/src/HStream/Server/Initialization.hs
=> for new LogAttributes

script/dev-deploy, script/dev_deploy_conf_example.json
Main changes: add cfg for memory and cpus
---
=> [skip ci] dev-deploy: add cfg for memory and cpus

script/dev-deploy
Main changes: dev-deploy: add docker node-exporter
---
=> [skip-ci] dev-deploy: add docker node-exporter

common/proto/HStream/Server/HStreamApi.proto, hstream-admin/HStream/Admin/Server/Types.hs, hstream/src/HStream/Server/Core/Stream.hs, hstream/src/HStream/Server/Exception.hs, hstream/src/HStream/Server/Handler/Query.hs, hstream/src/HStream/Server/Handler/View.hs, hstream/test/HStream/HandlerSpec.hs, hstream/test/HStream/SpecUtils.hs
=> add backlog retention to stream attrs

script/dev-deploy
=> [skip ci] dev-deploy: bug fix

script/dev-deploy, script/dev_deploy_conf_example.json
Main changes: add extra opts for scp cmd
---
=> [skip ci] dev-deploy: upload prometheus cfg dir

script/dev-deploy, script/dev_deploy_conf_example.json
Main changes: 
- fix wrong configuration path
- fix wrong type annotation
- fix zookeeper data not persisted
- support disable restart containers
---
=> [skip ci] update dev-deploy

hstream-store/HStream/Store/Internal/LogDevice/Writer.hs, hstream-store/HStream/Store/Stream.hs, hstream-store/cbits/logdevice/hs_writer.cpp, hstream-store/hstream-store.cabal, hstream-store/test/HStream/Store/SettingsSpec.hs, hstream-store/test/HStream/Store/SpecUtils.hs, hstream-store/test/HStream/Store/WriterSpec.hs, hstream/src/HStream/Server/Core/Stream.hs
=> fix a memory allocation bug in appendBatchBS

script/dev-deploy, script/dev_deploy_conf_example.json, script/prometheus-cfg/cluster.yml, script/prometheus-cfg/disks.yml, script/prometheus-cfg/memory_cpus.yml, script/prometheus-cfg/net.yml, script/prometheus-cfg/prometheus.yml
Main changes: 
- Integration with cadvisor
- update Prometheus config file
- bugfix
---
=> [skip ci] feat: support more metrics for promethus

hstream-store/HStream/Store/Stream.hs, hstream-store/test/HStream/Store/StreamSpec.hs, hstream/src/HStream/Server/Core/Stream.hs
=> code refactoring: archiveStream

.github/workflows/ci.yml
Main changes: run BasicTest by tag
---
=> fix: Run BasicTest by tag

common/stats/HStream/Stats.hs, common/stats/HStream/Stats/Internal.hs, common/stats/cbits/hs_stats.cpp, common/stats/cbits/stats/Stats.cpp, common/stats/cbits/stats/Stats.h, common/stats/include/per_subscription_stats.inc, common/stats/include/per_subscription_time_series.inc, common/stats/test/HStream/StatsSpec.hs
=> stats: add per_subscription_stats

hstream/src/HStream/Server/Handler/Stream.hs
Main changes: add retry for NOSEQUENCER
---
=> return StatusUnavailable while appends throw NOSEQUENCER

hstream/src/HStream/Server/Handler/Common.hs, hstream/src/HStream/Server/Handler/Subscription.hs, hstream/test/HStream/AckSpec.hs
Main changes: fix  incorrect way to subtract subUnackedRecords
---
=> fix: incorrect way to subtract subUnackedRecords

hstream/src/HStream/Server/Handler/Subscription.hs
Main changes: fix Map.! error, given key is not an element in the map
---
=> fix: Map.! error, given key is not an element in the map

common/stats/HStream/Stats.hs, common/stats/include/per_stream_time_series.inc, common/stats/include/per_subscription_stats.inc, common/stats/include/per_subscription_time_series.inc, common/stats/test/HStream/StatsSpec.hs, hstream/src/HStream/Server/Handler/Stream.hs, hstream/src/HStream/Server/Handler/Subscription.hs
=> more stats

common/HStream/Foreign.hs, common/stats/HStream/Stats.hs, common/stats/HStream/Stats/Internal.hs, common/stats/bench/stats.hs, common/stats/cbits/hs_stats.cpp, common/stats/cbits/stats/ServerHistograms.h, common/stats/cbits/stats/Stats.cpp, common/stats/cbits/stats/Stats.h, common/stats/include/hs_stats.h, common/stats/test/HStream/StatsSpec.hs, hstream/src/HStream/Server/Initialization.hs
Main changes: Support ServerHistogram
---
=> stats: new ServerHistogram stats

hstream/src/HStream/Server/Handler/Subscription.hs
Main changes: fix missing messages in case of resending without consumers
---
=> fix: missing messages in case of resending without consumers

common/stats/cbits/hs_stats.cpp
=> bug fixes: get histogram estimate percentiles should be aggregated

hstream/src/HStream/Server/Types.hs
Main changes: update `serverVersion`
---
=> release: update `serverVersion`

hstream-store/HStream/Store/Stream.hs
=> fix: remove incorrect cache of stream to logid

common/proto/HStream/Server/HStreamApi.proto
=> proto: minor improvements

common/stats/HStream/Stats.hs, common/stats/HStream/Stats/Internal.hs, common/stats/cbits/hs_stats.cpp, common/stats/cbits/stats/Stats.cpp, common/stats/cbits/stats/Stats.h, common/stats/include/per_handle_time_series.inc, common/stats/test/HStream/StatsSpec.hs, common/stats/test/HStream/StatsSpecUtils.hs
=> common: add per handle stats

Makefile, cabal.project, hie.yaml, hstream-gossip/CHANGELOG.md, hstream-gossip/app/Client.hs, hstream-gossip/app/Server.hs, hstream-gossip/hstream-gossip.cabal, hstream-gossip/proto/HStream/Gossip/HStreamGossip.proto, hstream-gossip/src/HStream/Client/Types.hs, hstream-gossip/src/HStream/Gossip.hs, hstream-gossip/src/HStream/Gossip/Core.hs, hstream-gossip/src/HStream/Gossip/Gossip.hs, hstream-gossip/src/HStream/Gossip/Handlers.hs, hstream-gossip/src/HStream/Gossip/Probe.hs, hstream-gossip/src/HStream/Gossip/Start.hs, hstream-gossip/src/HStream/Gossip/Types.hs, hstream-gossip/src/HStream/Gossip/Utils.hs, hstream-gossip/test/HStream/Gossip/EventSpec.hs, hstream-gossip/test/HStream/Gossip/FailureSpec.hs, hstream-gossip/test/HStream/Gossip/JoinSpec.hs, hstream-gossip/test/HStream/Gossip/TestUtils.hs, hstream-gossip/test/Spec.hs
Main Changes:
Add Package HStream Gossip:
- Probe for Failure Detection
- Gossip
=> add package hstream-gossip

hstream-admin/HStream/Admin/Server/Types.hs, hstream-admin/hstream-admin.cabal, hstream-connector/HStream/Connector/HStore.hs, hstream/hstream.cabal, hstream/src/HStream/Client/Action.hs, hstream/src/HStream/Server/Core/Stream.hs, hstream/src/HStream/Server/Handler.hs, hstream/src/HStream/Server/Handler/Cluster.hs, hstream/src/HStream/Server/Handler/Common.hs, hstream/src/HStream/Server/Handler/Query.hs, hstream/src/HStream/Server/Handler/Stream.hs, hstream/src/HStream/Server/Handler/Subscription.hs, hstream/src/HStream/Server/Initialization.hs, hstream/src/HStream/Server/ReaderPool.hs, hstream/src/HStream/Server/Types.hs, hstream/test/HStream/HandlerSpec.hs, hstream/test/HStream/SpecUtils.hs
=>  Merge "update shard model #932"

hstream-store/HStream/Store/Stream.hs, hstream/src/HStream/Server/Core/Stream.hs, hstream/src/HStream/Server/Handler.hs, hstream/src/HStream/Server/Handler/Cluster.hs, hstream/src/HStream/Server/Handler/Stream.hs, hstream/src/HStream/Server/Initialization.hs, hstream/src/HStream/Server/Persistence/Common.hs, hstream/src/HStream/Server/Types.hs
Main changes: 
- Add list shard handler
---
=> add list shards handler

hstream/src/HStream/Server/Core/Subscription.hs, hstream/src/HStream/Server/Persistence/Common.hs, hstream/src/HStream/Server/Persistence/Object.hs, hstream/src/HStream/Server/Types.hs
Main changes: 
- subscriptionOffset must be calculated when creating the subscription
---
=> subscriptionOffset must be calculated when creating the subscription

hstream/src/HStream/Client/Gadget.hs, hstream/src/HStream/Server/Core/Cluster.hs, hstream/src/HStream/Server/Handler.hs, hstream/src/HStream/Server/Handler/Cluster.hs
Main changes:
- replace lookupStream RPC to lookupShard RPC
---
=> replace lookupStream to lookupShard

common/HStream/Utils/BuildRecord.hs, hstream/hstream.cabal, hstream/src/HStream/Server/Core/Cluster.hs, hstream/src/HStream/Server/Core/Stream.hs, hstream/src/HStream/Server/HStore.hs, hstream/src/HStream/Server/Handler/Query.hs, hstream/src/HStream/Server/Handler/Stream.hs, hstream/src/HStream/Server/Persistence.hs, hstream/src/HStream/Server/Persistence/Common.hs, hstream/src/HStream/Server/Persistence/Exception.hs, hstream/src/HStream/Server/Persistence/ShardReader.hs, hstream/src/HStream/Server/Persistence/Utils.hs, hstream/src/HStream/Server/Types.hs
Main changes:
- persistence shardReader
- use shardId to verify append server node
---
=> Persistence Reader && Calculate consistency hash using shardId when append

common/HStream/Utils/BuildRecord.hs, hstream/src/HStream/Server/Config.hs, hstream/src/HStream/Server/Core/Query.hs, hstream/src/HStream/Server/Core/Stream.hs, hstream/src/HStream/Server/Core/Subscription.hs, hstream/src/HStream/Server/Core/View.hs, hstream/src/HStream/Server/Exception.hs, hstream/src/HStream/Server/HStore.hs, hstream/src/HStream/Server/Handler/Common.hs, hstream/src/HStream/Server/Handler/Query.hs, hstream/src/HStream/Server/Handler/Stream.hs
Main changes: 
- replace error to exception
---
=> replace error to exception

hstream-store/HStream/Store/Stream.hs, hstream-store/test/HStream/Store/StreamSpec.hs, hstream/src/HStream/Server/Core/Stream.hs, hstream/src/HStream/Server/Core/Subscription.hs, hstream/src/HStream/Server/HStore.hs
=> stop creating default partition automatically

common/HStream/Utils/RPC.hs, hstream/app/client.hs, hstream/src/HStream/Client/Action.hs, hstream/src/HStream/Client/Gadget.hs, hstream/src/HStream/Client/Internal.hs, hstream/src/HStream/Client/Types.hs, hstream/src/HStream/Server/Exception.hs
Main changes: add support for TLS
---
=> cli: add support for TLS

hstream/src/HStream/Server/Handler/Query.hs, hstream/src/HStream/Server/Types.hs
Main changes: improve ExecuteQuery err msg and upd server ver
---
=> chore: improve `ExecuteQuery` err msg and upd server ver

common/HStream/Utils.hs, common/HStream/Utils/BuildRecord.hs, common/HStream/Utils/Codec.hs, common/HStream/Utils/Compression.hs, common/HStream/bench/Bench.hs, common/HStream/bench/CodecBench.hs, common/HStream/bench/CompresstionBench.hs, common/HStream/bench/Util.hs, common/hstream-common.cabal, common/test/HStream/CodecSpec.hs, common/test/HStream/ConsistentHashingSpec.hs, hie.yaml, hstream/src/HStream/Client/Action.hs, hstream/src/HStream/Client/Internal.hs, hstream/src/HStream/Server/Core/Common.hs, hstream/src/HStream/Server/Core/Stream.hs, hstream/src/HStream/Server/Core/Subscription.hs, hstream/src/HStream/Server/HStore.hs, hstream/src/HStream/Server/Handler/Stream.hs, hstream/test/HStream/AdminCommandSpec.hs, hstream/test/HStream/HandlerSpec.hs, hstream/test/HStream/SpecUtils.hs, hstream/test/HStream/StatsIntegrationSpec.hs
=> support Compression

common/HStream/Utils/Compression.hs, common/bench/CompresstionBench.hs, common/hstream-common.cabal, common/test/HStream/CodecSpec.hs
Main changes: 
- add zstd compression algorithm
---
=> support zstd compression algo

common/stats/include/per_stream_time_series.inc
=> [skip ci] fix wrong metrics name

hstream-admin/HStream/Admin/Server/Types.hs, hstream/src/HStream/Server/Core/Stream.hs, hstream/src/HStream/Server/Core/Subscription.hs, hstream/src/HStream/Server/HStore.hs, hstream/src/HStream/Server/Handler/Stream.hs, hstream/src/HStream/Server/Handler/Subscription.hs, hstream/test/HStream/HandlerSpec.hs, hstream/test/HStream/SpecUtils.hs
Main changes: 
- add create timestamp for stream and subscription
---
=> add create timestamp for stream and subscription

common/HStream/Exception.hs, common/HStream/Utils.hs, common/HStream/Utils/Validation.hs, common/hstream-common.cabal, common/test/HStream/ValidationSpec.hs, hstream-diffflow/diff-flow.cabal, hstream-diffflow/src/DiffFlow/Shard.hs, hstream-io/HStream/IO/Worker.hs, hstream/src/HStream/Server/Core/Query.hs, hstream/src/HStream/Server/Handler/Stream.hs, hstream/src/HStream/Server/Handler/Subscription.hs
=> add module for validating names

hstream-store/HStream/Store/Stream.hs
=> bug fixes: disable stream local cache

common/HStream/Logger.hs
=> minor fixes: make hstream-common repl work

conf/hstream.yaml, hstream/src/HStream/Server/Config.hs, hstream/src/HStream/Server/Initialization.hs, hstream/test/HStream/ConfigSpec.hs
Main changes:
- support config checkpoint replication factor
---
=> support config checkpoint replication factor

conf/hstream.yaml
ref: https://github.com/hstreamdb/hstream-connectors/pull/29
=> feat: update io connectors version(v0.2.2)

common/hstream/HStream/Logger.hs, hstream-sql/hstream-sql.cabal, hstream/hstream.cabal
There is a known ghci bug that will cause repl fail, which seems fixed at ghc9.4
=> fix cabal repl

hstream/hstream.cabal, hstream/src/HStream/Server/Handler.hs, hstream/src/HStream/Server/Handler/Stats.hs, hstream/src/HStream/Server/HsGrpcHandler.hs
Main changes:
- refactor get stats handler
---
=> hserver: refactor get stats handler

hstream/src/HStream/Server/Handler/Stats.hs
Main changes: 
- add missing sub send out records failed stats handler
---
=> add sub send out records failed stats

common/hstream/HStream/Exception.hs
- Rename macros
- Exception: add CallStack for HStreamException
=> Exception: add CallStack for SomeHServerException

common/hstream/HStream/Exception.hs, common/hstream/HStream/Utils/Validation.hs, common/hstream/test/HStream/ValidationSpec.hs, hie.yaml, hstream/hstream.cabal, hstream/src/HStream/Server/Core/Cluster.hs, hstream/src/HStream/Server/Core/Query.hs, hstream/src/HStream/Server/Core/Stream.hs, hstream/src/HStream/Server/Core/Subscription.hs, hstream/src/HStream/Server/Core/View.hs, hstream/src/HStream/Server/HStore.hs, hstream/src/HStream/Server/Handler/Common.hs, hstream/src/HStream/Server/Handler/Connector.hs, hstream/src/HStream/Server/Handler/Query.hs, hstream/src/HStream/Server/Handler/Stream.hs, hstream/src/HStream/Server/Handler/Subscription.hs, hstream/src/HStream/Server/Handler/View.hs, hstream/src/HStream/Server/Types.hs, hstream/src/HStream/Server/Validation.hs
Main changes: 
- Checks only the handler that modify the resource (e.g. create*, delete*)
- Removed checks for handlers that do not create resources (e.g. list*)
---
=> add handler validation

common/hstream/HStream/Utils/RPC.hs, hstream/src/HStream/Server/Core/Common.hs, hstream/src/HStream/Server/Core/Stream.hs
=> update publish timestamp when read

common/stats/HStream/Stats.hs, common/stats/HStream/Stats/Internal.hs, common/stats/cbits/hs_stats.cpp, common/stats/cbits/stats/Stats.cpp, common/stats/cbits/stats/Stats.h, common/stats/include/per_query_stats.inc, hstream-processing/hstream-processing.cabal, hstream-processing/src/HStream/Processing/Processor.hs, hstream/src/HStream/Server/Handler/Common.hs, hstream/src/HStream/Server/Handler/Query.hs, hstream/src/HStream/Server/Handler/Stats.hs
=> add query stat

common/stats/HStream/Stats.hs, common/stats/include/per_query_stats.inc, hstream-processing/src/HStream/Processing/Processor.hs, hstream/src/HStream/Server/Handler/Stats.hs
=> add query execute error stat

hstream/src/HStream/Server/Core/ShardReader.hs
=> remove set timeout for readShardStream

common/stats/HStream/Stats.hs, common/stats/HStream/Stats/Internal.hs, common/stats/cbits/hs_stats.cpp, common/stats/cbits/stats/Stats.cpp, common/stats/cbits/stats/Stats.h, common/stats/include/per_view_stats.inc, hstream/src/HStream/Server/Core/View.hs, hstream/src/HStream/Server/Handler/Stats.hs
=> add view stats

common/hstream/HStream/Utils/Format.hs
=> cli: print query name when show views

hstream/src/HStream/Server/Core/ShardReader.hs
=> fix timeout setting for shardReader

hstream/src/HStream/Server/Core/Subscription.hs
=> fix ckpReader config

hstream-processing/src/HStream/Processing/Processor.hs, hstream/src/HStream/Server/Handler/Common.hs
=> fix query stats

common/stats/HStream/Stats.hs, common/stats/HStream/Stats/Internal.hs, hstream-admin/server/HStream/Admin/Server/Types.hs, hstream/src/HStream/Server/Handler/Admin.hs
=> hadmin-server: add stats command for connector, query and view

common/stats/HStream/Stats.hs, common/stats/HStream/Stats/Internal.hs, common/stats/cbits/hs_stats.cpp, common/stats/cbits/stats/Stats.h, common/stats/hstream-common-stats.cabal, common/stats/test/HStream/StatsSpec.hs
- New feature
- stats: remove unused packages
- stats: add erase method
=> Stats erase

hstream-sql/src/HStream/SQL/Codegen/Cast.hs, hstream-sql/src/HStream/SQL/Codegen/V1.hs
=> sql: refine and fix cast operation

hstream-sql/src/HStream/SQL/Codegen/BinOp.hs
=> sql: fix `IFNULL`

common/hstream/HStream/Utils/Format.hs, hstream/app/client.hs, hstream/hstream.cabal, hstream/src/HStream/Client/Action.hs, hstream/src/HStream/Client/Execute.hs, hstream/src/HStream/Client/Types.hs, hstream/src/HStream/Client/Utils.hs, hstream/src/HStream/Server/Core/ShardReader.hs
=> cli: add read shard command

.github/workflows/publish.yml, .github/workflows/publish_latest.yml
Main changes: 
- fetch all tags before get version info
---
=> [skip ci] ci: fetch all tags before get version info

hstream-admin/server/HStream/Admin/Server/Types.hs, hstream/src/HStream/Server/Handler/Admin.hs
Main changes: 
- add admin server lookup subcommand
```
> hadmin server lookup query cli_generated_jkivsxaalk
+--------------------------+-----------+-------+
|       Resource ID        |   Host    | Port  |
+--------------------------+-----------+-------+
| cli_generated_jkivsxaalk | 127.0.0.1 | 45803 |
+--------------------------+-----------+-------+
```
---
=> admin server: add lookup subcommand

common/hstream/HStream/Utils/Format.hs, common/hstream/HStream/Utils/RPC.hs, hstream-admin/app/admin.hs, hstream-admin/server/HStream/Admin/Server/Command.hs, hstream-admin/server/HStream/Admin/Server/Types.hs, hstream/src/HStream/Server/Core/Query.hs, hstream/src/HStream/Server/Core/View.hs, hstream/src/HStream/Server/Handler/Admin.hs, hstream/src/HStream/Server/Handler/Query.hs, hstream/src/HStream/Server/MetaData/Types.hs
Main changes: 
- add hadmin server query command
```
> hadmin server --port 6570 query describe --id cli_generated_jkivsxaalk
+--------------------------+--------------+---------+-----------+-----------+-------------+------+-------------------------------------------------------+
|         Query ID         |     Type     | Status  | Source ID | Result ID | CreatedTime | Node |                          SQL                          |
+--------------------------+--------------+---------+-----------+-----------+-------------+------+-------------------------------------------------------+
| cli_generated_jkivsxaalk | CreateViewAs | RUNNING | s1        | v1        | 1685418429  | 1    | create view v1 as select count(*) from s1 group by a; | …
```
=> add hadmin server query

common/hstream/HStream/Utils/RPC.hs, hstream-admin/app/admin.hs, hstream-admin/server/HStream/Admin/Server/Command.hs, hstream-admin/server/HStream/Admin/Server/Types.hs, hstream-io/HStream/IO/IOTask.hs, hstream-io/HStream/IO/Types.hs, hstream-io/HStream/IO/Worker.hs, hstream-io/hstream-io.cabal, hstream/src/HStream/Server/Handler/Admin.hs, hstream/src/HStream/Server/Handler/Connector.hs
Main changes: 
- add hadmin server connector list
```
> hadmin server connector list
+----------------+--------+-----------+---------+---------------+
| Connector Name |  Type  |  Target   | Status  | Created Time  |
+----------------+--------+-----------+---------+---------------+
| source1        | SOURCE | generator | RUNNING | 1685606755000 |
| sink1          | SINK   | blackhole | RUNNING | 1685606763000 |
+----------------+--------+-----------+---------+---------------+
```
- add hadmin server connector describe
```
> hadmin server connector describe --id sink1
+----------------+--------------------------------------+----------------+-----------+---------+---------+----------------------+---------------------------------+---------------+
| Connector Name |               Task ID …
```
=> add hadmin server connector

hstream-admin/app/admin.hs, hstream-admin/server/HStream/Admin/Server/Types.hs, hstream/src/HStream/Server/Handler/Subscription.hs
=> hadmin server: fix command needs lookup

hstream/app/client.hs, hstream/src/HStream/Client/Types.hs
=> cli: add hstream version

hstream-sql/etc/SQL-v1.cf, hstream-sql/etc/SQL-v2.cf, hstream-sql/etc/syntax-test-cases.yaml, hstream-sql/src/HStream/SQL/AST.hs, hstream-sql/src/HStream/SQL/Codegen/Cast.hs, hstream-sql/src/HStream/SQL/Codegen/V1.hs, hstream-sql/src/HStream/SQL/Extra.hs, hstream-sql/src/HStream/SQL/Internal/Validate.hs, hstream/test/HStream/RegressionSpec.hs
Main changes: `extractHIdent` now will fold for cases
---
=> SQL: improve syntax for quotes, stage 1

hstream-sql/etc/SQL-v1.cf, hstream-sql/src/HStream/SQL/AST.hs, hstream-sql/src/HStream/SQL/Codegen/UnaryOp.hs, hstream-sql/src/HStream/SQL/Internal/Validate.hs, hstream/src/HStream/Server/Core/Common.hs, hstream/src/HStream/Server/Core/Query.hs
=> SQL: operator `NOT`

hstream-sql/etc/syntax-test-cases.yaml, hstream-sql/src/HStream/SQL/AST.hs, hstream-sql/src/HStream/SQL/Codegen/V1.hs, hstream-sql/src/HStream/SQL/Extra.hs, hstream-sql/src/HStream/SQL/Internal/Validate.hs
=> sql: fix refine string literal

hstream/src/HStream/Server/Core/Common.hs, hstream/src/HStream/Server/Core/Subscription.hs, hstream/src/HStream/Server/Types.hs
Main changes:
- Add logs to the subscription section
- Fix the implementation of Ord CheckedRecordIds
---
=> add log for subscription

hstream/src/HStream/Server/Core/Subscription.hs
=> check waitingConsumer list when invalid a consumer

hstream/src/HStream/Server/Core/Subscription.hs
=> fix wrong set of checklist_size stats

common/hstream/HStream/Utils/Format.hs, common/hstream/HStream/Utils/RPC.hs, hstream/app/client.hs
Main changes: 
- format grpc io error  as: `errorMsg: extra`
e.g. "StreamNotFound: At least one of the streams/views do not exist: [\"s4\"]"
---
=> cli: format grpc io error

hstream/app/server.hs, hstream/src/HStream/Server/Core/Cluster.hs, hstream/src/HStream/Server/Core/Common.hs, hstream/src/HStream/Server/Handler/Admin.hs, hstream/src/HStream/Server/Handler/Cluster.hs, hstream/src/HStream/Server/Handler/Connector.hs, hstream/src/HStream/Server/Handler/Query.hs, hstream/src/HStream/Server/Handler/ShardReader.hs, hstream/src/HStream/Server/Validation.hs
=> validate resourceId when lookup resource

common/base/hstream-common-base.cabal
=> Remove unused extra libraries for hstream-common-base

common/hstream/HStream/Utils/Validation.hs, hstream/src/HStream/Server/Handler/Cluster.hs
=> fix validate lookup request

hstream-sql/etc/SQL-v1.cf, hstream-sql/etc/syntax-test-cases.yaml, hstream-sql/hstream-sql.cabal, hstream-sql/src/HStream/SQL/AST.hs, hstream-sql/src/HStream/SQL/Codegen/Cast.hs, hstream-sql/src/HStream/SQL/Codegen/Common.hs, hstream-sql/src/HStream/SQL/Codegen/TerOp.hs, hstream-sql/src/HStream/SQL/Extra.hs, hstream-sql/src/HStream/SQL/Internal/Validate.hs, hstream-sql/src/HStream/SQL/Planner.hs, hstream-sql/src/HStream/SQL/Planner/Pretty.hs
=> sql: `BETWEEN`

hstream/src/HStream/Client/SQL.hs
=> cli: update sql help info

hstream-sql/etc/syntax-test-cases.yaml
=> sql: add more syntax test cases

common/hstream/HStream/Exception.hs, hstream-store/HStream/Store/Internal/LogDevice/Reader.hs, hstream-store/HStream/Store/Stream.hs, hstream/app/client.hs, hstream/hstream.cabal, hstream/src/HStream/Server/Core/ShardReader.hs, hstream/src/HStream/Server/Handler/ShardReader.hs, hstream/src/HStream/Server/Types.hs
=> add maxReadBatches and endRecordId to readShardStream handler

hstream/app/client.hs, hstream/src/HStream/Client/Types.hs, hstream/src/HStream/Server/Core/ShardReader.hs
=> cli: update stream read-shard command

hstream-sql/etc/SQL-v1.cf, hstream-sql/src/HStream/SQL/AST.hs, hstream-sql/src/HStream/SQL/Codegen/V1.hs, hstream-sql/src/HStream/SQL/Internal/Validate.hs, hstream/hstream.cabal, hstream/src/HStream/Client/Action.hs, hstream/src/HStream/Client/SQL.hs, hstream/src/HStream/Server/Core/Query.hs, hstream/src/HStream/Server/Handler/Common.hs
=> sql: insert select

hstream-sql/etc/SQL-v1.cf, hstream-sql/etc/SQL-v2.cf, hstream-sql/etc/syntax-test-cases.yaml, hstream-sql/src/HStream/SQL/AST.hs, hstream/hstream.cabal
=> sql: refine create connector syntax

common/hstream/HStream/Exception.hs, hstream-store/HStream/Store/Stream.hs, hstream/src/HStream/Server/Core/ShardReader.hs, hstream/src/HStream/Server/Handler.hs, hstream/src/HStream/Server/Handler/ShardReader.hs, hstream/src/HStream/Server/HsGrpcHandler.hs, hstream/src/HStream/Server/Types.hs
Main changes: 
- add ReadStream RPC
- fixed incorrect timing of readerStopReading calls
---
=> add ReadStream RPC

hstream-sql/etc/SQL-v1.cf, hstream-sql/etc/SQL-v2.cf, hstream-sql/etc/syntax-test-cases.yaml
Main changes: will close #1491
---
=> sql: refine array syntax

hstream-sql/src/HStream/SQL/Codegen/V1.hs, hstream/app/client.hs, hstream/src/HStream/Client/Action.hs, hstream/src/HStream/Client/SQL.hs, hstream/src/HStream/Client/Types.hs, hstream/test/HStream/SpecUtils.hs
=> cli: add stream append command

common/hstream/HStream/Utils/Format.hs
=> refactor format API.ReceivedRecord

conf/hstream.yaml, hstream/src/HStream/Server/Config.hs, hstream/test/HStream/ConfigSpec.hs
=> modify default store replica to 1

common/hstream/HStream/Exception.hs, hstream-store/test/HStream/StoreSpec.hs, hstream/src/HStream/Server/ConnectorTypes.hs, hstream/src/HStream/Server/Core/ShardReader.hs, hstream/src/HStream/Server/Core/Stream.hs, hstream/src/HStream/Server/Handler.hs, hstream/src/HStream/Server/Handler/Stream.hs, hstream/src/HStream/Server/HsGrpcHandler.hs, hstream/src/HStream/Server/Types.hs
Main changes: 
- move `ToOffset` type class to Types.hs
- add trimShard rpc
- add trimStream rpc
---
=> add trimStream && trimShard rpc

docker/docker-compose.yaml, docker/logdevice.json, hstream-store/bench/checkpoint_store.cpp
- Update docker-compose.yaml to use a zk cluster
- [skip ci] Store: add a checkpointStore bench
=> Add a checkpointStore bench

hstream/src/HStream/Server/Handler/ShardReader.hs
=> fix shardReader for grpc-haskell

common/hstream/HStream/Common/ZookeeperSlotAlloc.hs, hstream/src/HStream/Server/Core/Stream.hs, hstream/src/HStream/Server/Experimental/StreamV2.hs, hstream/src/HStream/Server/Handler/Stream.hs
=> Experimental feature stream-v2

hstream/src/HStream/Server/Core/ShardReader.hs, hstream/src/HStream/Server/Handler/ShardReader.hs, hstream/src/HStream/Server/Types.hs
=> fix incorrect number of record entries delivered by readStreamByKey

hstream/src/HStream/Server/Core/Cluster.hs, hstream/src/HStream/Server/Handler.hs, hstream/src/HStream/Server/Handler/Cluster.hs, hstream/src/HStream/Server/HsGrpcHandler.hs
=> add LookupKey rpc

conf/hstream.yaml, hstream-io/HStream/IO/IOTask.hs, hstream-io/HStream/IO/Worker.hs, hstream/src/HStream/Server/Core/Query.hs, hstream/src/HStream/Server/Handler/Connector.hs
* improve recoverConnector, deleteConnector APIs
* simplify stdout handling
=> fix(connector): improve connector robustness

cabal.project, hstream-sql/src/HStream/SQL/Binder/Select.hs, hstream-store/hstream-store.cabal, hstream/app/server.hs, hstream/hstream.cabal, hstream/src/HStream/Client/SQL.hs
- add hstream_store_enable_asan flag
- add hstream_enable_asan flag
=> Support ASan

hstream/app/client.hs
=> fix(cli): encode HRecord when append

hstream/src/HStream/Client/Types.hs
=> cli: refactor shardOffset parser

hstream/src/HStream/Server/Core/ShardReader.hs
=> fix: readStream can not consume multi-shard stream

common/hstream/HStream/Common/Types.hs, common/hstream/hstream-common.cabal, hstream/app/client.hs, hstream/hstream.cabal, hstream/src/HStream/Client/SQL.hs, hstream/src/HStream/Client/Utils.hs, hstream/src/HStream/Server/Core/ShardReader.hs, hstream/src/HStream/Server/Core/Stream.hs, hstream/src/HStream/Server/HStore.hs, hstream/src/HStream/Server/Shard.hs, hstream/src/HStream/Server/Types.hs, hstream/test/HStream/ShardSpec.hs
=> Fix calculateShardId

hstream/src/HStream/Server/Handler/Stream.hs
=> make PEER_UNAVAILABLE a retryable exception

hstream-sql/src/HStream/SQL/Binder/Select.hs
=> sql: improve schema not found errmsg

common/stats/HStream/Stats.hs, common/stats/cbits/stats/ServerHistograms.h, common/stats/include/per_stream_stats.inc, hstream/src/HStream/Server/Core/ShardReader.hs, hstream/src/HStream/Server/Core/Subscription.hs, hstream/src/HStream/Server/Handler/Common.hs, hstream/src/HStream/Server/Handler/Stats.hs, hstream/src/HStream/Server/Types.hs
=> add read stream metrics

common/kafka/hstream-kafka.cabal, common/kafka/src/Kafka/Protocol/Error.hs
=> hstream-kafka: add ErrorCode constants

hstream/src/HStream/Server/Core/Stream.hs
=> fix Ord instance for Rid

hstream/app/client.hs, hstream/src/HStream/Client/Internal.hs, hstream/src/HStream/Client/Types.hs
=> cli: use the interactive shell to execute hstream append

hstream/src/HStream/Server/Core/ShardReader.hs, hstream/src/HStream/Server/Types.hs
=> set read timeout for reader in readStreamByKey

hstream/src/HStream/Server/Core/Stream.hs
=> ignore Earliest Position when trimShards

hstream/src/HStream/Server/Experimental/StreamV2.hs, hstream/src/HStream/Server/Handler.hs, hstream/src/HStream/Server/Handler/Stats.hs, hstream/src/HStream/Server/HsGrpcHandler.hs
=> export connector IsAlives stats

hstream-admin/store/HStream/Admin/Store/Command/Logs.hs, hstream-admin/store/HStream/Admin/Store/Types.hs
=> cli(hadmin-store): support update replicate-across attribute

hstream/src/HStream/Server/Types.hs
=> hstream-server: until time lsn should not greater than current tail lsn

common/hstream/HStream/Utils/Common.hs, hstream-kafka/HStream/Kafka/Client/Cli.hs, hstream-kafka/cbits/hs_kafka_client.cpp, hstream/src/HStream/Client/Internal.hs
=> kafka-cli: polish kafka cli

conf/hstream.yaml, hstream-kafka/HStream/Kafka/Client/Cli.hs, hstream-kafka/HStream/Kafka/Network.hs, hstream-kafka/HStream/Kafka/Server/Config/FromCli.hs, hstream-kafka/HStream/Kafka/Server/Config/FromJson.hs, hstream-kafka/HStream/Kafka/Server/Config/Types.hs, hstream-kafka/HStream/Kafka/Server/Core/Topic.hs, hstream-kafka/HStream/Kafka/Server/Handler/Basic.hs, hstream-kafka/HStream/Kafka/Server/Handler/Topic.hs, hstream-kafka/HStream/Kafka/Server/Types.hs, hstream-kafka/hstream-kafka.cabal
=> kafka: support auto create topic

common/server/HStream/Common/Server/MetaData.hs, hstream-kafka/HStream/Kafka/Group/GroupOffsetManager.hs, hstream-kafka/hstream-kafka.cabal, hstream/app/kafka-server.hs
=> kafka: use groupName to fetch consumer offsets from store

hstream-kafka/HStream/Kafka/Common/Utils.hs, hstream-kafka/HStream/Kafka/Group/GroupOffsetManager.hs, hstream-kafka/HStream/Kafka/Metrics/ConsumeStats.hs, hstream-kafka/HStream/Kafka/Metrics/ProduceStats.hs, hstream-kafka/HStream/Kafka/Metrics/ServerStats.hs, hstream-kafka/HStream/Kafka/Network.hs, hstream-kafka/HStream/Kafka/Server/Handler/Consume.hs, hstream-kafka/HStream/Kafka/Server/Handler/Produce.hs, hstream-kafka/hstream-kafka.cabal, hstream/app/kafka-server.hs, hstream/hstream.cabal
=> Kafka metrics

conf/hstream.yaml, hstream-kafka/HStream/Kafka/Server/Config/FromCli.hs, hstream-kafka/HStream/Kafka/Server/Config/FromJson.hs, hstream-kafka/HStream/Kafka/Server/Config/Types.hs, hstream-kafka/HStream/Kafka/Server/Handler/Basic.hs, hstream/app/lib/KafkaServer.hs
=> kafka: support set metrics port

common/hstream/HStream/Exception.hs, hstream/src/HStream/Server/Core/ShardReader.hs, hstream/src/HStream/Server/Handler/ShardReader.hs
=> hserver: handle unrecoverable gaptype for shardReader 

hstream-kafka/HStream/Kafka/Common/Metrics/ConsumeStats.hs, hstream-kafka/HStream/Kafka/Group/GroupCoordinator.hs, hstream-kafka/HStream/Kafka/Group/GroupOffsetManager.hs
=> kafka: add commit offset request counter

hstream-kafka/HStream/Kafka/Client/Cli.hs
=> kafka(cli): fix listGroups should list all groups in the cluster

hstream-kafka/HStream/Kafka/Server/Handler.hsc, hstream-kafka/HStream/Kafka/Server/Handler/Topic.hs, hstream-kafka/protocol/Kafka/Protocol/Message/Struct.hs, hstream-kafka/protocol/Kafka/Protocol/Message/Total.hs, script/kafka_gen.py
=> kafka: upgrade DeleteTopics to version 1

hstream-kafka/HStream/Kafka/Server/Core/Topic.hs, hstream-kafka/HStream/Kafka/Server/Handler.hsc, hstream-kafka/HStream/Kafka/Server/Handler/Basic.hs, hstream-kafka/HStream/Kafka/Server/Handler/Topic.hs, hstream-kafka/protocol/Kafka/Protocol/Message/Struct.hs, hstream-kafka/protocol/Kafka/Protocol/Message/Total.hs, script/kafka_gen.py
=> kafka: upgrade CreateTopics to version 2

hstream-kafka/HStream/Kafka/Server/Handler/Offset.hs, hstream-kafka/cbits/hs_kafka_client.cpp
=> kafka(cli): set isolation level to read_uncommited

hstream-kafka/HStream/Kafka/Group/GroupOffsetManager.hs, hstream-kafka/HStream/Kafka/Group/OffsetsStore.hs, hstream-kafka/HStream/Kafka/Server/Core/Topic.hs, hstream-kafka/HStream/Kafka/Server/Handler.hsc, hstream-kafka/HStream/Kafka/Server/Handler/Topic.hs, hstream-kafka/message/CreatePartitionsRequest.json, hstream-kafka/message/CreatePartitionsResponse.json, hstream-kafka/protocol/Kafka/Protocol/Message/Struct.hs, hstream-kafka/protocol/Kafka/Protocol/Message/Total.hs, script/kafka_gen.py
=> kafka: support CreatePartitions

hstream/app/server.hs, hstream/src/HStream/Server/Handler/ShardReader.hs, hstream/src/HStream/Server/Handler/Stats.hs
=> hserver: catch exception for stats handler and gossip nodeChangeEvent

hstream-kafka/HStream/Kafka/Server/Config/KafkaConfigManager.hs, hstream-kafka/HStream/Kafka/Server/Core/Topic.hs
=> kafka: validate topic name in listTopicConfigs

hstream-kafka/HStream/Kafka/Group/Group.hs, hstream-kafka/HStream/Kafka/Group/GroupCoordinator.hs, hstream-kafka/HStream/Kafka/Group/GroupOffsetManager.hs, hstream-kafka/HStream/Kafka/Server/Config/KafkaConfig.hs, hstream-kafka/HStream/Kafka/Server/Types.hs
=> kafka: support set group initialRebalaceDelay

hstream-kafka/HStream/Kafka/Server/Config.hs, hstream-kafka/HStream/Kafka/Server/Config/FromCli.hs, hstream-kafka/HStream/Kafka/Server/Config/FromJson.hs, hstream-kafka/HStream/Kafka/Server/Config/KafkaConfig.hs, hstream-kafka/HStream/Kafka/Server/Config/Types.hs, hstream-kafka/hstream-kafka.cabal, hstream-kafka/tests/HStream/Kafka/Common/ConfigSpec.hs
=> kafka: fix merge configs

.github/workflows/publish.yml, .github/workflows/publish_latest.yml
Since using "cache" will cause
> ERROR: failed to solve: cannot copy from stage "cache", it needs to be defined before current stage "builder"
=> [workaround]docker build: no cache

hstream/src/HStream/Server/Handler/Cluster.hs
=> hserver: fix log level

script/kafka_gen.py
=> [skip ci] kafka_gen.py: bug fixes
