hstreamdb/hstream

hstream-store/HStream/Store/Internal/LogDevice/LogConfigTypes.hs
hstream-store/admin/HStream/Store/Admin/Command.hs
hstream-store/admin/HStream/Store/Admin/Command/Logs.hs
hstream-store/admin/HStream/Store/Admin/Types.hs
hstream-store/admin/app/cli.hs
hstream-store/admin/hstore-admin.cabal

Implemented logdevice shell command `logs info` using optparser in Haskell
Fixes #163 
Run
```
cabal build all
cabal run -- hstore-admin --port 42666 logs info --id 1
```

ldshell: command "logs info"

---

hstream-server/app/Server.hs
hstream-server/hstream-server.cabal
hstream-server/src/HStream/Server/HStoreConnector.hs
hstream-server/src/HStream/Server/Handler.hs
hstream-server/src/HStream/Server/Persistence.hs
hstream-server/src/HStream/Server/Utils.hs
hstream-sql/hstream-sql.cabal
hstream-sql/src/HStream/SQL/AST.hs
hstream-sql/src/HStream/SQL/Codegen.hs
hstream-sql/src/HStream/SQL/Codegen/Utils.hs
hstream-sql/src/HStream/SQL/Validate.hs
hstream/HStream/Format.hs
hstream/client/Main.hs
hstream/hstream.cabal

- Improve CLI format with an external library 
- add zk persistence library to keep all queries executed
- add show queries to show all queries 
- replace task name from "demo" to the hex of current timestamp
New feature (non-breaking change which adds functionality)
TODO

Add persistence

---

hstream/src/HStream/Server/HStoreConnector.hs

A `SELECT` query will get the last message in the database with the old semantic of `Latest` offset. The proper semantic is to start from `tailLSN + 1`.

fix the semantic of `Latest` offset

---

hstream/app/server.hs
hstream/src/HStream/Server/Handler.hs
hstream/src/HStream/Server/Persistence.hs

query stores in memory set as default

hstream-server: query stores in memory set as default

---

hstream-store/HStream/Store/Exception.hs
hstream-store/admin/HStream/Store/Admin/Command/Logs.hs
hstream-store/admin/HStream/Store/Admin/Types.hs

hstore admin functionality: remove a log group or a log directory.
Fixes #219 
```
>>> cabal run -- hstore-admin --port 46003 logs remove --path "test/"
NOTFOUND
>>>cabal run -- hstore-admin --port 46003 logs create --path "test/" --directory
SUCCESS
>>>cabal run -- hstore-admin --port 46003 logs create --path "test/group" --from 111 --to 123
SUCCESS
>>>cabal run -- hstore-admin --port 46003 logs remove --path "test/group"
SUCCESS
>>>cabal run -- hstore-admin --port 46003 logs remove --path "test/group"
NOTFOUND
>>>cabal run -- hstore-admin --port 46003 logs create --path "test/group" --from 111 --to 123
SUCCESS
>>>cabal run -- hstore-admin --port 46003 logs remove --path "test/" --recursive
SUCCESS
>>>cabal run -- hstore-admin --port 46003 logs remove --path "test/group"
NOTFOUND
```

hstore admin: logs remove

---

hstream-store/HStream/Store/Internal/LogDevice/LogConfigTypes.hs
hstream-store/cbits/logdevice/hs_logconfigtypes.cpp
hstream-store/test/HStream/Store/LogDeviceSpec.hs

An hstore api that will be used by the cli command `logs show`.
En route to fix #221 
See `LogDeviceSpec.hs`

hstore api: logDirLogsName

---

hstream-store/HStream/Store/Internal/LogDevice/LogConfigTypes.hs
hstream-store/HStream/Store/Stream.hs
hstream-store/admin/HStream/Store/Admin/Command/Logs.hs
hstream-store/admin/HStream/Store/Admin/Types.hs
hstream-store/admin/hstore-admin.cabal
hstream-store/cbits/logdevice/hs_logconfigtypes.cpp
hstream-store/include/hs_logdevice.h
hstream-store/test/HStream/Store/LogDeviceSpec.hs

Added HStore Admin command `logs show`
Fixes #221 
```
>>>cabal run -- hstore-admin --port 44439 logs create --path "/group" --from 123 --to 123 --extra-attributes "A":"B"
SUCCESS
>>>cabal run -- hstore-admin --port 44439 logs show -v
- /
Version: 373662155212
* /test_logs (1..100)
Version: 373662155212
Attributes:
- replication factor: 2
* /group (123..123)
Version: 373662155212
Attributes:
- replication factor: 3
- A: B
- /hstream/
Version: 373662155212
- /ci/
Version: 373662155212
- /ci/stream/
Version: 373662155212
>>>cabal run -- hstore-admin --port 44439 logs show
- /
* /test_logs (1..100)
* /group (123..123)
- /hstream/
- /ci/
- /ci/stream/
>>>cabal run -- hstore-admin --port 44439 logs show --id 123 -v
* /group (123..123)
Version: 373662155212
Attributes:
- replication factor: 3
- …
```

hstore admin: command `logs show`

---

hstream-store/HStream/Store/Internal/Foreign.hs
hstream-store/HStream/Store/Internal/LogDevice/LogConfigTypes.hs
hstream-store/cbits/logdevice/hs_logconfigtypes.cpp
hstream-store/include/hs_logdevice.h
hstream-store/test/HStream/Store/LogDeviceSpec.hs

Implemented a hstore api which will be used by the command `logs set-range`.
Fixes # (issue)
New testcases are added to `LogDeviceSpec.hs`

hstore api: logGroupSetRange

---

hstream-store/admin/HStream/Store/Admin/Command/Logs.hs
hstream-store/admin/HStream/Store/Admin/Types.hs

Implemented ldshell command `logs set-range` to update the range of a log group.
En route to fixes #274

hstore admin: command `logs set-range`

---

hstream-store/HStream/Store.hs
hstream-store/HStream/Store/Internal/LogDevice.hs
hstream-store/HStream/Store/Internal/LogDevice/LogConfigTypes.hs
hstream-store/HStream/Store/Internal/Types.hsc
hstream-store/admin/HStream/Store/Admin/Command/Logs.hs
hstream-store/cbits/hs_logdevice.cpp
hstream-store/include/hs_logdevice.h

Added hstore api `isLogEmpty` and prints the information when `logs info` is called
Fixes #289

hstore admin: logs info prints whether the log is empty

---

hstream-connector/HStream/Connector/HStore.hs
hstream-sql/src/HStream/SQL/Codegen.hs
hstream-store/HStream/Store/Internal/Types.hsc
hstream/app/server.hs
hstream/common/hstream-common.cabal
hstream/common/src/HStream/Utils.hs
hstream/common/src/HStream/Utils/BuildRecord.hs
hstream/src/HStream/Server/Handler.hs
hstream/test/HStream/RunSQLSpec.hs

Update `executeQueryHandler` to support `HStreamRecord` format.
Add an extra `InsertType` field to `InsertPlan` constructor, so that we can use it to distinguish the specific storage format when we need to construct `HStreamRecord`. 

hstream-server: support HStreamRecord format

---

hstream-sql/etc/SQL.cf

Users usually use some function names such as `SUM` and `COUNT` as self-defined identifiers. For example,
```
SELECT SUM(a) as sum, COUNT(*) as count FROM foo GROUP BY b EMIT CHANGES;
```
However, the query will not get parsed because `SUM` and `COUNT` are reserved keywords. In this PR, function names with a `(` become reserved keywords rather than function names themselves.

hstream-sql: allow function names to be used as user-defined identifiers

---

hstream/common/proto/HStream/Server/HStreamApi.proto
hstream/src/HStream/Server/Handler.hs

Implement `listSubscriptions` and `deleteSubscribe` grpc
Ensure that the `subscriptionId` and `reader` correspond to each other.

hstream-server: implement listSubscriptions and deleteSubcribe grpc

---

hstream/src/HStream/Server/Handler.hs
hstream/src/HStream/Server/Handler/Common.hs
hstream/src/HStream/Server/Handler/Connector.hs
hstream/src/HStream/Server/Handler/Query.hs
hstream/src/HStream/Server/Handler/View.hs

I made ServerNormalResponse possible to allow Nothing to be returned when errors occur, and this PR is adapted to the latest hstreamdb/gRPC-haskell.

fix(server): fix ServerNormalResponse

---

common/proto/HStream/Server/HStreamApi.proto
hstream/app/server.hs
hstream/hstream.cabal
hstream/src/HStream/Server/Handler.hs
hstream/src/HStream/Server/Handler/Common.hs
hstream/test/HStream/HandlerSpec.hs

Add a `sendConsumerHeartbeat` rpc to let a client send a heartbeat to server. When server receives the rpc, it will update the set of subscribed subscriptionId, release unused subscriptionId so that other client can subscribe it using the same id.

hstream-server: refactor handlers to support resubscribe subscription with same subscriptionId

---

hstream/src/HStream/Server/Handler.hs
hstream/test/HStream/HandlerSpec.hs

Bugfix: after `deleteSubscription`, send heartbeat should return an error, but currently return success.
Unit test

hstream-server: fix send heartbeat after deleteSubscription return success

---

hie.yaml
hstream-store/bench/AppendBatchBench.hs
hstream-store/bench/AppendBench.hs
hstream-store/hstream-store.cabal

| Table      | Time | Space |
| ----------- | ----------- | ----------|
| 100 * 1KB Bytes       |  286 μs      | 24KB |
| 100 * 1KB BS           | 301 μs       | 20KB  |
| 1000 * 1KB Bytes       |  932 μs      | 240KB |
| 1000 * 1KB BS           | 946 μs       | 200KB  |
| 100 * 1MB Bytes       |  42 ms      | 24KB |
| 100 * 1MB BS           | 38 ms       | 20KB  |

hstore: add benchmark on appendBatch

---

common/proto/HStream/Server/HStreamApi.proto
hstream/app/server.hs
hstream/src/HStream/Server/Exception.hs
hstream/src/HStream/Server/Handler.hs
hstream/src/HStream/Server/Handler/Common.hs
hstream/test/HStream/HandlerSpec.hs

1. Separate `SubscribeHandler` to `CreateSubscribeHandler` and `SubscribeHandler`.
2. Support consumer read from the checkpoint.
Unit test

hstream-server: refactor subscribe

---

hstream-sql/src/HStream/SQL/AST.hs

namely we can `parseAndRefine` the following now:
```haskell
parseAndRefine "SELECT `SUM(a)` FROM my_view WHERE b = 1;"
```

sql: fix pattern matching coverage on `RawColumn`

---

.github/workflows/ci.yml

For now, if 8.8.4 job failed, 8.10.4 will be canceled.

ci: preventing a specific failing matrix job from failing a workflow run

---

hstream-sql/src/HStream/SQL/Codegen.hs
hstream/src/HStream/Server/Handler/Query.hs

```sql
> select * from v2 where y = 0;
{"winStart = 1631977513274":{"x":49.0,"SUM(x)":49.0}}
> select x from v2 where y = 0;
{"winStart = 1631977513274":{"x":49.0}}
> select `SUM(x)` from v2 where y = 0;
{"winStart = 1631977513274":{"SUM(x)":49.0}}
> select a from v2 where y = 0;
{}
```
```sql
> select * from v1 where y = 0;
{"x":49.0,"SUM(x)":49.0}
> select x from v1 where y = 0;
{"x":49.0}
> select `SUM(x)` from v1 where y = 0;
{"SUM(x)":49.0}
> select a from v1 where y = 0;
{}
```
```sql
> select a from v where y = 0;
{}
> select x from v where y = 0;
{"winStart = 1631977280000 ,winEnd = 1631977290000":{"x":49.0}}
> select * from v where y = 0;
{"winStart = 1631977280000 ,winEnd = 1631977290000":{"x":49.0,"SUM(x)":49.0}}
```
----------------
```sql
> select * from v3 where x = 0; …
```

sql: filter result of `SELECT` from view, return exception when search cond isn't in create

---

script/dev-tools

Now, bash history is available inside `dev-tool shell`
---

dev-tools: enable bash_history

---

hstream/src/HStream/Server/Handler/Subscription.hs

Main changes: 
1. fix point read lastLSN may get an empty list and cause an exception in the doRead function
2. fix wrong use of zipWithM
---

hstream-server: Fix `head` operation on an empty list returned by point read lastLSN

---

hstream/src/HStream/Server/Config.hs

log-level option parser shouldn't have a default value
---

remove the default value in log-level option

---

hstream/src/HStream/Server/Handler/Common.hs
hstream/src/HStream/Server/Handler/Subscription.hs
hstream/test/HStream/AckSpec.hs

Main changes:
- Fix `streamingfetch` data loss
- Fix `insertAckedRecordId` can't deal with duplicate acked record
---

hstream-server: streamingfetch bug fix

---

common/HStream/Utils/RPC.hs
common/proto/HStream/Server/HStreamApi.proto
hstream/src/HStream/Server/Initialization.hs
hstream/src/HStream/Server/Persistence/Nodes.hs
hstream/src/HStream/Server/Persistence/Utils.hs

Main changes: 
Every server node, when it starts, will write info of itself into the same persistent node.
---

write status while starting a server node

---

hstream-sql/src/HStream/SQL/Parse.hs
hstream/src/HStream/Server/Exception.hs
hstream/src/HStream/Server/Handler/Common.hs
hstream/src/HStream/Server/Handler/Query.hs
hstream/src/HStream/Server/Handler/StoreAdmin.hs
hstream/src/HStream/Server/Handler/Subscription.hs
hstream/src/HStream/Server/Handler/View.hs
hstream/src/HStream/Server/InternalHandler.hs

Main changes: 
- regulating the use of grpc error code
---

hstream-server: Regulating the use of grpc error code

---

common/HStream/Utils/RPC.hs
hstream/src/HStream/Server/Exception.hs
hstream/src/HStream/Server/Handler/Query.hs
hstream/src/HStream/Server/Handler/Subscription.hs

- fix: create a consumer with existing consumerName should return an error
---

hstream-server: create duplicated consumer should return error

---

docker/quick-start.yaml

Main changes:   simplify quickstart by using docker volume instead of user's data dir
---

simplify quickstart by using docker volume instead of user's data dir

---

common/HStream/Utils/BuildRecord.hs
common/proto/HStream/Server/HStreamApi.proto
hstream-store/test/HStream/Store/StreamSpec.hs
hstream/src/HStream/Server/Core/Stream.hs
hstream/src/HStream/Server/Handler/Common.hs
hstream/src/HStream/Server/Handler/Stream.hs
hstream/src/HStream/Server/Persistence/Utils.hs

Main changes: 
- support partition for creating stream and append to stream
- modify deleteStream proto to support force delete a stream
- refine the deleteStream function
Details:
- add a new zookeeper path `/hstreamdb/streams/{streamName}/keys/{key}` to support dynamic partitioning
-  Path `/hstreamdb/streams/{streamName}/keys/` will be created in `createStream` function, and the sub path
`xxx/{streamName}/xxx` will be removed in `deleteStream` function.
- when server receive an append request with a new partition key, it will create the sub path `xxx/{streamName}/keys/{key}`, then other servers can be notified by watching the path `xxx/{streamName}/keys`.
---
- New and …

hstream-server: support partition for creating, delete and append to a stream

---

hstream-admin/HStream/Admin/Server/Command/ServerSql.hs
hstream-admin/HStream/Admin/Store/Command/SQL.hs
hstream-sql/etc/SQL.cf
hstream-sql/src/HStream/SQL/AST.hs
hstream-sql/src/HStream/SQL/Codegen.hs
hstream-sql/src/HStream/SQL/Internal/Validate.hs
hstream/app/client.hs

Main changes:
- fix built-in Ctrl-C handling
- remove `hstream-client` admin stats table
---

cli: abort on `C-c`, rm client-admin stats table

---

.github/workflows/ci.yml

Main changes: only run basic tests, upload logs
---

ci: only run basic tests, upload logs

---

hstream/src/HStream/Server/Exception.hs
hstream/src/HStream/Server/Handler/Stream.hs

Main changes: set grpc status to unavailable when append failed in case of unprepared log group, client will retry. 
---

fix: fix append error when log group is not prepared

---

hstream/src/HStream/Server/Handler/Subscription.hs
hstream/src/HStream/Server/Types.hs

Main changes: 
fix: concurrent calls to the ldreader to read the retransmitted data will result in a coredump
---

hstream-server: protect ldreader with MVar

---

hstream/src/HStream/Server/Types.hs

Main changes: The Ord definition of ConsumerWorkload should satisfy the properties of a total order, or may cause some unexpected behavior(e.g. Set.delete, https://github.com/hstreamdb/hstream/blob/78fd6d6c9bab7898bef6de15442b6635733d0728/hstream/src/HStream/Server/Handler/Subscription.hs#L696).
---

fix: Ord definition of ConsumerWorkload

---

hstream-store/HStream/Store/Stream.hs
hstream/hstream.cabal
hstream/src/HStream/Server/Shard.hs
hstream/test/HStream/ShardSpec.hs

Main changes: 
- `ShardKey` is an integer that represents a value in the space of consecutive keys. Users can use the MD5 algorithm to map the actual business key to a value in the key space.
- `Shard` indicates a Shard of a stream. Each time a `Shard` can be split into two shards, or two adjacent shards can be merged into one shard.
- `ShardMap` maps Starkey to a specific Shard. `ShardMap` allows the user to locate the shard to which the specified ShardKey belongs.
- `SharedShardMap` allocates 16 slots, each of which has a `ShardMap` protected by TMVar. User finds the corresponding `ShardMap` in the `SharedShardMap` by the ShardKey first, and then can perform other operations safely
---
- I have **comment**ed my code, particularly in …

add Shard module to support manipulate shards

---

hstream/src/HStream/Server/Core/Stream.hs
hstream/src/HStream/Server/Handler/Query.hs
hstream/src/HStream/Server/Handler/Subscription.hs
hstream/src/HStream/Server/Handler/View.hs
hstream/src/HStream/Server/Initialization.hs
hstream/src/HStream/Server/Shard.hs
hstream/src/HStream/Server/Types.hs
hstream/test/HStream/HandlerSpec.hs
hstream/test/HStream/RegressionSpec.hs
hstream/test/HStream/RunSQLSpec.hs
hstream/test/HStream/ShardSpec.hs

Main changes: 
- Add a `ShardDict` for each stream. `ShardDict` map Starkey to shardId. OrderingKey from append request will be hashed by MD5, then use the hash value to find its target shardId from `ShardDict`
- Each stream has a SharedShardMap that holds shard-related information in memory and supports subsequent split/merge operations on all shards in the stream
---

Update write read shard

---

hstream/src/HStream/Server/Core/Subscription.hs

This can cause severe inconsistency between `subConsumerContexts` and `shard2Consumer`, which leads to a forever read-send-retry loop. The appearance of the bug is one or more message is lost.

bug fixed: a shard can be assigned to an invalid consumer

---

hstream/app/client.hs
hstream/src/HStream/Client/Types.hs

Main changes: add `-e --execute` for sql
```sh
I have no name!@inductive:~/re/repl/hstream/hstream$ cabal run hstream -- sql -e 'create stream sss;'
Up to date
sss
I have no name!@inductive:~/re/repl/hstream/hstream$ cabal run hstream -- sql -e 'create stream ssss;'
Up to date
ssss
I have no name!@inductive:~/re/repl/hstream/hstream$ cabal run hstream -- sql -e 'insert into stream s (x, y) values (32, 20);'
Up to date
Parse exception at <line 1,column 13>: syntax error before `STREAM'.
I have no name!@inductive:~/re/repl/hstream/hstream$ cabal run hstream -- sql -e 'insert into  s (x, y) values (32, 20);'
I have no name!@inductive:~/re/repl/hstream/hstream$ cabal run hstream -- sql --execute 'insert into  s (x, y) values (32, 20);'
Up to date
Done.
I have no …
```

hstream app: add `-e --execute` for sql

---

hstream-sql/src/HStream/SQL/Exception.hs
hstream/app/client.hs
hstream/app/server.hs

Main changes:
```
> select
| *
| from
| s
| emit
| changes
| ;
^CTerminated
> show streams
| ;
+----------------------+---------+----------------+-------------+
| Stream Name          | Replica | Retention Time | Shard Count |
+----------------------+---------+----------------+-------------+
| juqlTVOFCAvGfHHMIPqE | 1       | 0sec           | 1           |
+----------------------+---------+----------------+-------------+
| ZSHhwSTZAiACReNLwkfQ | 1       | 0sec           | 1           |
+----------------------+---------+----------------+-------------+
| aKyGZDCkdeUmFIBamDtW | 1       | 0sec           | 1           |
+----------------------+---------+----------------+-------------+
| TgDNyMLAxEsbkKVMEuGx | 1       | 0sec           | 1           | …
```

cli: enter multi-line mode when throwing EOF

---

hstream/app/client.hs
hstream/src/HStream/Client/Types.hs

Main changes:
- fix a bug that admin command does not parse
- add history and opts for cli
```
I have no name!@inductive:~/hstream/hstream$ cabal run hstream -- sql --history-file=$PWD/.hstream_history
> create stream sss;
sss
> create
| stream
| ssss;
ssss
> select * from s emit changes;
^CTerminated
> show streams;
```
```
show streams;
select * from s emit changes;
create stream ssss;
create stream sss;
create stream ss;
```
---

cli: history and bug fix

---

hstream-sql/src/HStream/SQL/AST.hs
hstream-sql/src/HStream/SQL/Exception.hs

Main changes:
```
> select * from s emit changes
| 
| 
Parse exception syntax error at end of file: expected a ";" at the end of a statement.
> select * from s emit changes;
^CTerminated
> 
I have no name!@inductive:~/re-fk/hstream/hstream$ cabal run hstream -- sql -e 'select * from s emit changes'
Up to date
Parse exception syntax error at end of file: expected a ";" at the end of a statement.
```
---

hstream-sql: err msg for missing `;`

---

hstream/src/HStream/Server/Config.hs

Main changes: fix a probable typo in `max-record-size` option validation
---

fix `max-record-size` option validation

---

hstream/app/client.hs
hstream/src/HStream/Client/Types.hs

usage：
```
> hstream nodes check-running -n 3
All nodes in the cluster are running.
```

add check-running subcommand for hstream nodes 

---

hstream/app/server.hs
hstream/src/HStream/Server/Config.hs
hstream/test/HStream/ConfigSpec.hs

Format: ` <listener_key>:hstream://<address>:<port>`
Equivalent to the following in the configuration file:
```
<listener_key>:
- address: <address>
port: <port>
```
Usage:
```
hstream-server --advertised-listeners public:hstream://192.168.1.190:6580 --advertised-listeners public:hstream://192.168.1.190:6590 
```

 add server `advertised-listeners` options 

---

hstream/src/HStream/Server/Handler/Subscription.hs

* All metadata keys must be lowercase in gRPC.

fix uppercase grpc metadata keys

---

hie.yaml
hstream-store/HStream/Store/Internal/LogDevice/Reader.hs
hstream/src/HStream/Server/Core/Subscription.hs

Main changes: 
- set default 10 ms timeout for reader
- retry when reader read get null records
- fix hie.yaml
---

fix: retry when resend reader read null records

---

hstream/src/HStream/Server/Core/Subscription.hs

set timeout for ldCkpReader to avoid stuck forcing delete subscription

---

hstream-sql/etc/SQL-v1.cf
hstream-sql/etc/SQL-v2.cf
hstream-sql/src/HStream/SQL/Extra.hs
hstream-sql/src/HStream/SQL/Internal/Validate.hs
hstream-sql/test/HStream/SQL/ParseRefineSpec.hs
script/format.sh
script/start-server.sh

Main changes: deny unquoted dash in ident
raw error
```
> select a->>"season_id" from production_changes EMIT CHANGES;
Parse exception at <line 1,column 11>: syntax error before `>'.
> EXPLAIN SELECT a->b FROM s2;
-------- RAW PLAN --------
Project (name=a->b, alias=a->b) []
Affiliate (name=a->b, expr=OpGT(#(a-), #(b))) 
StreamScan s2
```
The above parse error and mistaken parse is caused by “a-“ is a valid HIdent, which is a valid simple col name, which is a val expr. If we add a space on the Left of arrow it will works.
`a->number` can be parsed as either “Extracts n'th element of JSON array (array elements are indexed from zero, but negative integers count from the end).“, the ColName a  > number. a->”str” can be parsed as select field “str“ or ColName a- compare to str
---
- I have …

sql: deny unquoted dash in ident

---

hstream/hstream.cabal
hstream/src/HStream/Server/Core/Subscription.hs
hstream/src/HStream/Server/Types.hs

- use `heap` intead of `list` for inflight recordsIds
- remove `subWaitingCheckedRecordIdsIndex` and simplify releated code

refactor data structures of inflight recordIds in subscription

---

hstream-admin/server/HStream/Admin/Server/Types.hs
hstream/src/HStream/Server/Handler/Admin.hs
hstream/src/HStream/Server/MetaData/Types.hs
hstream/src/HStream/Server/Types.hs

Main changes: 
- meta list -r [subscription|query-info|view-info|qv-relation]
```
hadmin server meta list -r subscription
+---------------------------------------------------+--------------------------------------------------------+------------+---------------------+---------------+------------+----------------------------------+
|                      Sub ID                       |                       StreamName                       | AckTimeout | Max Unacked Records |  CreatedTime  | OffsetType |             Offsets              |
+---------------------------------------------------+--------------------------------------------------------+------------+---------------------+---------------+------------+----------------------------------+
| …
```

Hadmin meta

---

common/hstream/HStream/Utils/Format.hs
hstream/app/client.hs
hstream/src/HStream/Client/Action.hs
hstream/src/HStream/Client/Types.hs
hstream/src/HStream/Server/Core/ShardReader.hs

Main changes: 
- cli support read-stream command
- fix: terminate serverStreaming when the timestamp of the record is greater than until timestamp
---

cli: add read-stream command

---

Makefile
hstream-sql/hstream-sql.cabal
hstream-sql/src/HStream/SQL/AST.hs
hstream-sql/src/HStream/SQL/Codegen/AggOp.hs
hstream-sql/src/HStream/SQL/Codegen/BinOp.hs
hstream-sql/src/HStream/SQL/Codegen/Cast.hs
hstream-sql/src/HStream/SQL/Codegen/ColumnCatalog.hs
hstream-sql/src/HStream/SQL/Codegen/Common.hs
hstream-sql/src/HStream/SQL/Codegen/TerOp.hs
hstream-sql/src/HStream/SQL/Codegen/UnaryOp.hs
hstream-sql/src/HStream/SQL/Codegen/V1.hs
hstream-sql/src/HStream/SQL/Codegen/V1/Boilerplate.hs
hstream-sql/src/HStream/SQL/Exception.hs
hstream-sql/src/HStream/SQL/Internal/Check.hs
hstream-sql/src/HStream/SQL/Internal/Validate.hs
hstream-sql/src/HStream/SQL/Planner.hs
hstream-sql/src/HStream/SQL/Planner/Pretty.hs
hstream-sql/src/HStream/SQL/Validate/Utils.hs

hstream-sql: code clean up

---

hstream/src/HStream/Server/Core/ShardReader.hs
hstream/src/HStream/Server/Types.hs

Main changes: 
The behavior of LATEST OFFSET differs when it serves as the starting point and the endpoint for the shardReader. 
- When it is the starting point, it should return the LSN of the next record to be written. 
- When it is the endpoint, it should return the LSN of the last record in the current log.
---

fix different action for latest offset

---

hstream/src/HStream/Server/Core/ShardReader.hs
hstream/src/HStream/Server/Handler.hs
hstream/src/HStream/Server/Handler/ShardReader.hs
hstream/src/HStream/Server/HsGrpcHandler.hs
hstream/src/HStream/Server/Types.hs

Main changes: 
pseudocode for main read loop
```
while {
nextRoundReads <- streamRecv
if (nextRoundReads == 0) break
// send cached records fist
if (cachedRecords not empty) {
streamSend cachedRecords
nextRoundReads -= cachedSize
}
while (nextRoundReads > 0) {
records <- decompress <$> logdeviceReader read
(needSend, cached) <- split nextRoundReads records
streamSend needSend
nextRoundReads -= sendRecordSize
update cache
}
}
```
---

add ReadStreamByKey rpc

---

hstream/src/HStream/Server/Core/ShardReader.hs

Main changes: 
- fix: readStreamByKey should close server stream when until offset reached
- set default until offset to tail lsn
---

fix: ReadStreamByKey rpc should close server stream when until offset reached

---

hstream-gossip/src/HStream/Gossip/Start.hs
hstream-gossip/src/HStream/Gossip/Types.hs
hstream/app/server.hs

fix dead lock when client send init before server already bootstrap

---

hstream/src/HStream/Server/Core/ShardReader.hs

Main changes: 
- When executing readStream, some shards may not meet the user-specified offset and should be skipped to continue execution.
---

cli: fix read-stream --from timestamp --until latest may fail

---

conf/hstream.yaml
hstream-kafka/HStream/Kafka/Server/Config/FromJson.hs
hstream-kafka/HStream/Kafka/Server/Config/KafkaConfig.hs
hstream-kafka/HStream/Kafka/Server/Config/KafkaConfigManager.hs
hstream-kafka/HStream/Kafka/Server/Config/Types.hs
hstream-kafka/HStream/Kafka/Server/Core/Topic.hs
hstream-kafka/HStream/Kafka/Server/Handler/Basic.hs
hstream-kafka/HStream/Kafka/Server/Types.hs

* add KafkaConfigs class
* add parseBrokerConfigs: automatically parse Kafka broker configs

fix(kafka): improve kafka configs

---

hstream-kafka/HStream/Kafka/Common/Metrics/ConsumeStats.hs
hstream-kafka/HStream/Kafka/Common/Metrics/ProduceStats.hs
hstream-kafka/HStream/Kafka/Server/Handler/Consume.hs
hstream-kafka/HStream/Kafka/Server/Handler/Produce.hs
hstream-kafka/HStream/Kafka/Server/Handler/Topic.hs

Main changes: 
- fix incorrect errorCode:
If two clients, a and b, perform the following operations concurrently: listTopic >>= deleteTopic, then in the delete handler, even if `S.doesStreamExist` returns true, the subsequent deletion may still throw a `NOTFOUND` exception. In this case, this exception would be incorrectly mapped to `UNKNOWN_SERVER_ERROR`, rather than `UNKNOWN_TOPIC_OR_PARTITION`.
- fix read latency tracking for consume handler
---

kafka: fix exception handle for delete topic and read latency tracking

---

hstream-kafka/HStream/Kafka/Client/Cli.hs
hstream-kafka/cbits/hs_kafka_client.cpp

Main changes: 
```shell
$ hstream-kafka-cli --port 9092 consume -g c15 -t test-t --earliest -v
CreateTimestamp: 1703818135548   Key:                      vvv
CreateTimestamp: 1703669800783   Key:                      pfg
CreateTimestamp: 1703673787567   Key:                      dddd
CreateTimestamp: 1703661884636   Key: k3                   ccc
CreateTimestamp: 1703818141791   Key:                      vvvv
CreateTimestamp: 1703661880207   Key: k2                   bbb
CreateTimestamp: 1703661870948   Key: k1                   aaa
```
---

kafka: Optimizing the output of consume cli

---

hstream-kafka/HStream/Kafka/Server/Handler.hsc
hstream-kafka/HStream/Kafka/Server/Handler/Offset.hs
hstream-kafka/protocol/Kafka/Protocol/Message/Struct.hs
hstream-kafka/protocol/Kafka/Protocol/Message/Total.hs
script/kafka_gen.py

kafka: upgrade ListOffsets to version 2

---

cabal.project.hadmin.store

constrain unordered-containers to < 0.2.20

hadmin-store: fix builds

---

hstream/src/HStream/Server/Handler/Stream.hs

chore(hserver): return empty if trimShards request send empty recordIds

---

conf/hstream.yaml
hstream-kafka/HStream/Kafka/Group/GroupCoordinator.hs
hstream-kafka/HStream/Kafka/Group/GroupOffsetManager.hs
hstream-kafka/HStream/Kafka/Group/OffsetsStore.hs
hstream-kafka/HStream/Kafka/Server/Config/FromCli.hs
hstream-kafka/HStream/Kafka/Server/Config/FromJson.hs
hstream-kafka/HStream/Kafka/Server/Config/KafkaConfig.hs
hstream-kafka/HStream/Kafka/Server/Config/KafkaConfigManager.hs
hstream-kafka/HStream/Kafka/Server/Config/Types.hs
hstream-kafka/HStream/Kafka/Server/Types.hs
hstream/app/lib/KafkaServer.hs

Main changes:
- support set broker property from cli, e.g. --prop num.partitions=2 --prop auto.create.topics.enable=false
- support set offset topic replica
---

kafka: support set broker property from cli

---

hstream-kafka/HStream/Kafka/Group/Group.hs
hstream-kafka/HStream/Kafka/Server/Handler/Group.hs

fix(kafka): verify coordinator for describe groups request

---

conf/hstream.yaml
hstream-admin/store/HStream/Admin/Store/Command/Logs.hs
hstream-kafka/HStream/Kafka/Server/Config/FromJson.hs
hstream-kafka/HStream/Kafka/Server/Config/Types.hs
hstream-kafka/HStream/Kafka/Server/Core/Topic.hs
hstream-store/HStream/Store/Internal/LogDevice/LogAttributes.hs
hstream-store/cbits/logdevice/hs_log_attributes.cpp
hstream-store/test/HStream/Store/LogDeviceSpec.hs

add `scdEnabled`, `localScdEnabled` and `stickyCopySets` log attributes

---

hstream-admin/app/admin.hs
hstream-admin/server/HStream/Admin/Server/Types.hs
hstream/src/HStream/Server/Handler/Admin.hs

hadmin: Update cli command

---

hstream-admin/server/HStream/Admin/Server/Types.hs
hstream/src/HStream/Server/Handler/Admin.hs
hstream/src/HStream/Server/MetaData/Types.hs

add admin cli command to support list and clean connector related meta data

---

common/server/HStream/Common/Server/Lookup.hs
hstream-io/HStream/IO/Meta.hs
hstream-io/HStream/IO/Types.hs
hstream-io/HStream/IO/Worker.hs
hstream/src/HStream/Server/Handler/Admin.hs

hadmin: remove the "node" field from the result of the listConnector command
